### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by TemeEmpada** [jvdutra/open-source-rpg#8]
Oi, verifiquei que da pra adicionar outros tipos de status, como mana, sanidade, inventário e outros. Para fazer a adição desses status tem que fazer alguma alteração no código, ou na própria dashboard do mestre consigo? Se der para colocar na própria dashboard do mestre, como faço?

**Comment by jvdutra** [comment]
Tem que ter conhecimentos de programação pra criar essas outras coisas. Se vc não tem, aguarda a versão com isso sair. Ainda não fizemos

**Comment by TemeEmpada** [comment]
Tudo beeem, obrigado! :D
