### ISSUE TITLE
Problemas ao carregar imagens de personagem

### ISSUE THREAD

**Issue by TaisBaierle** [jvdutra/open-source-rpg#9]
Não está deixando eu colocar imagens, 
![image](https://user-images.githubusercontent.com/49797949/143353418-a6d3eedd-cc31-4ec8-9e4c-7b4dd957750b.png)

As duas imagens estão no imgur:
https://imgur.com/7CYOBUu
https://imgur.com/oqIRx2z

Já verifiquei formato e tamanho e está ok

**Comment by Toupeirabeta** [comment]
Clica com o dedo direito do mouse na imagem e abre ela em uma nova aba, e ai sim vc copia a url/link pra jogar na ficha, o link tem que ficar com .png no final assim ó
![image](https://user-images.githubusercontent.com/90200022/143356657-fd279d3b-ee43-46c3-8642-6bd4a5408e8f.png)

**Comment by TaisBaierle** [comment]
Boa, brigada
